### ISSUE TITLE
是否支持将脚本注入到sprin容器中？

### ISSUE THREAD

**Issue by Yanghf123** [tianxiao-zp/wuzhu-FaaS#6]
如果有一个策略类，是否可以通过加载的方式 增加新的策略，动态上下线新的策略代码

**Comment by tianxiao-zp** [comment]
可以模拟实现。
比如当前策略工厂
Strategy{
   Map<String, Handler> factory = new HashMap<String, Handler>();
   public void init() {
        //这里的一般实现是利用spring bean初始化流程，在服务启动过程中对 factory 做策略初始化
   }
}
通过脚本容器来实现的话，可利用通过实现com.tianxiao.faas.runtime.processor.BeanDefinitionsAfterProcessor接口，可以参考SpringBeanDefinitionsAfterProcessor 的思路。
在脚本编译实例化之后，在processor类中通过反射的方式把实现了Handler接口的脚本放入Strategy的factory工厂里面。
这种方案属于特殊定制化的方案。
可以考虑把这个方案做的更通用一点也可以的。

还有一种方案：
可以通过脚本之间嵌套调用来实现，脚本可以通过：
ExecutorFactory executorFactory = ExecutorFactory.getInstance();
Executor executor = executorFactory.getExecutor(ExecutorType.GROOVY);
ExecutorContext executeContext = new ExecutorContext();
executeContext.setCode(code);
executeContext.setDebug(true);
executeContext.setParams(Lists.newArrayList(new UserBean()));
executeContext.setMethodName("test");
Object execute = executor.execute(executeContext);
来实现脚本调用，脚本里面也可以使用这段代码的哦。但一般不建议这样使用，这样使用之后很难维护。

不知道是否解答了你的问题，可以继续交流。
